name: Deploy Cloud Function

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Set up Google Cloud SDK
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT_KEY }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy daily_weather_ingestion \
            --runtime python311 \
            --trigger-http \
            --service-account weather-sa@vibrant-shell-455019-h3.iam.gserviceaccount.com \
            --allow-unauthenticated \
            --entry-point=daily_call \
            --region=europe-west3 \
            --source=src \
            --set-secrets=EMAIL_PASSWORD=projects/vibrant-shell-455019-h3/secrets/email_password/versions/latest \
            --set-secrets=API_KEY=projects/vibrant-shell-455019-h3/secrets/api_key/versions/latest

      - name: Deploy Cloud Scheduler
        run: |
          gcloud scheduler jobs create http weather-job \
            --schedule "0 7 * * *" \ 
            --uri "https://europe-west3-vibrant-shell-455019-h3.cloudfunctions.net/daily_weather_ingestion" \
            --http-method GET \
            --service-account weather-sa@vibrant-shell-455019-h3.iam.gserviceaccount.com
